### ISSUE TITLE
Where is JeyDevv?

### ISSUE THREAD

**Issue by Software-Wolf** [jeydevv/MonkeModMenu#4]
Looking for any way to get in touch with JeyDevv, I think his discord got banned or something because no one seems to know where he went... He left the gorilla tag modding server. If anyone has contact with him, please send me.

**Comment by jeydevv** [comment]
I didn't get banned, just had too many community members messaging me every day asking irrelevant or random things. I will not be working on any Gorilla Tag-related software any time soon.

Thanks,
Jeydevv
