### ISSUE TITLE
JeyDevv Let's Do Business - I'm Willing to Pay $$$$

### ISSUE THREAD

**Issue by Software-Wolf** [jeydevv/MonkeModMenu#5]
Hey JeyDevv, you may have realized a lot of mods broke during the new update, if you could please kindly give me a way to efficiently contact you, I would love to pay you to fix some mods including your super monkey mod. I will pay you like $50 for like 30 mins of work :)

**Comment by Software-Wolf** [comment]
@jeydevv

**Comment by jeydevv** [comment]
Sorry, I don't mod Gorilla Tag at the moment and am very busy right now - please stop opening issues to try and contact me.

Thanks,
Jeydevv

**Comment by Software-Wolf** [comment]
Sorry for bugging you, you were just the most advanced programmer in the modding community. If you ever change your mind my discord is notch#0904. Thank you for your reply.

**Comment by jeydevv** [comment]
No worries, I appreciate the praise - I'll let you know if I change my mind.

Thanks,
Jeydevv
